language: r
env:
  matrix:
  - LINTR_COMMENT_BOT=true
  global:
    secure: IGjuf04BkEr6fYG3/M75zdE7/IbYOyi0yVpsPLMpBzJQHHBtv7Qn02tRTLj4HSGVs5ZNZAib8xHMuP+qoIskh3JTQLBDLqVjEDQAjTIYoSYzw0AeVLA+S8NgncS+acmgzosGhsOUuKCx53AJBo9J8Zn1MpFWtU7acfKVTNTxfEI=

r_binary_packages:
- Rcpp
- testthat

r_github_packages:
- jimhester/covr
- jimhester/lintr

script:
- make install
- make check
- make test

after_success:
- Rscript -e 'lintr::lint_package()'
- Rscript -e 'covr::codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && bash .gh-pages-update.sh
