sudo: required
services:
  - docker
env:
  matrix:
  - LINTR_COMMENT_BOT=true
  global:
  - secure: Z6B4cfVy35zX71imDZbJe2RIG5s0CoU5Vkezgnb3HkrvlNLiRvjqimlDCEnltwlcLoNgUqaBsaxGB7bum5+hn/TUYnvvVsAA8xaMQgH6P2Rfa9zU0lko/7DfvUluuhHRrFRaNca2Gj/cf0Mbce90W2q8MtxP5bpPuVSqd6GbWYI=

before_install:
- docker pull rocker/hadleyverse
- docker run --rm -ti rocker/hadleyverse

script:
- make install
- make check
- make test
after_success:
- Rscript -e 'lintr::lint_package()'
- Rscript -e 'covr::codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash .gh-pages-update.sh
