language: r
env:
  matrix:
  - LINTR_COMMENT_BOT=true
  global:
  - secure: Z6B4cfVy35zX71imDZbJe2RIG5s0CoU5Vkezgnb3HkrvlNLiRvjqimlDCEnltwlcLoNgUqaBsaxGB7bum5+hn/TUYnvvVsAA8xaMQgH6P2Rfa9zU0lko/7DfvUluuhHRrFRaNca2Gj/cf0Mbce90W2q8MtxP5bpPuVSqd6GbWYI=
r_binary_packages:
- Rcpp
- testthat
r_github_packages:
- jimhester/covr
- jimhester/lintr
script:
- make install
- make check
- make test
after_success:
- Rscript -e 'lintr::lint_package()'
- Rscript -e 'covr::codecov()'
- bash .gh-pages-update.sh
